### ISSUE TITLE
Cartes PNG

### ISSUE THREAD

**Issue by BlueSpaceCookie** [HE-Arc/bourg-nell#7]
Trouver un jeu de 36 cartes au format PNG. Carte suisse de préférence

**Comment by BlueSpaceCookie** [comment]
Création des cartes :

https://www.blogduwebdesign.com/ressourcescreer-manipuler-cartes-html-javascript-nodejs-ruby/#creacuteer_un_design_de_carte_personnaliseacute

**Comment by lucalaissue** [comment]
Found some good quality images on jassfederal.ch
